Added two annotations Dao and Inject and Custom exception
vicire/jv-create-annotation pull request #2
Opened 2021-01-10 15:56 UTC by vicire

2021-01-10 16:38 UTC, Max-Pochepets approved these changes

2021-01-11 09:08 UTC, RomanDubovskyi requested changes
nice, left one minor comment

2021-01-11 09:08 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/lib/Injector.java
> +                    throw new NoSuchAnnotationException("There are no such anotation" + MARKER);
```suggestion
                    throw new NoSuchAnnotationException("There is no such anotation" + MARKER);
```
let's make message more informative and add class that is missing required annotation

2021-01-11 10:28 UTC, RomanDubovskyi approved these changes

2021-01-11 13:03 UTC, merged